<?php

use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $municipios = [
            ['codigo' => 3822, 'nome' => 'Agua Santa', 'uf' => 'RS'],
            ['codigo' => 3823, 'nome' => 'Agudo', 'uf' => 'RS'],
            ['codigo' => 3824, 'nome' => 'Ajuricaba', 'uf' => 'RS'],
            ['codigo' => 3825, 'nome' => 'Alecrim', 'uf' => 'RS'],
            ['codigo' => 3826, 'nome' => 'Alegrete', 'uf' => 'RS'],
            ['codigo' => 3827, 'nome' => 'Alegria', 'uf' => 'RS'],
            ['codigo' => 3828, 'nome' => 'Alpestre', 'uf' => 'RS'],
            ['codigo' => 3829, 'nome' => 'Alto Alegre', 'uf' => 'RS'],
            ['codigo' => 3830, 'nome' => 'Alto Feliz', 'uf' => 'RS'],
            ['codigo' => 3831, 'nome' => 'Alvorada', 'uf' => 'RS'],
            ['codigo' => 3832, 'nome' => 'Amaral Ferrador', 'uf' => 'RS'],
            ['codigo' => 3833, 'nome' => 'Ametista do Sul', 'uf' => 'RS'],
            ['codigo' => 3834, 'nome' => 'Andre da Rocha', 'uf' => 'RS'],
            ['codigo' => 3835, 'nome' => 'Anta Gorda', 'uf' => 'RS'],
            ['codigo' => 3836, 'nome' => 'Antonio Prado', 'uf' => 'RS'],
            ['codigo' => 3837, 'nome' => 'Arambare', 'uf' => 'RS'],
            ['codigo' => 3838, 'nome' => 'Ararica', 'uf' => 'RS'],
            ['codigo' => 3839, 'nome' => 'Aratiba', 'uf' => 'RS'],
            ['codigo' => 3840, 'nome' => 'Arroio do Meio', 'uf' => 'RS'],
            ['codigo' => 3841, 'nome' => 'Arroio do Sal', 'uf' => 'RS'],
            ['codigo' => 3842, 'nome' => 'Arroio do Tigre', 'uf' => 'RS'],
            ['codigo' => 3843, 'nome' => 'Arroio dos Ratos', 'uf' => 'RS'],
            ['codigo' => 3844, 'nome' => 'Arroio Grande', 'uf' => 'RS'],
            ['codigo' => 3845, 'nome' => 'Arvorezinha', 'uf' => 'RS'],
            ['codigo' => 3846, 'nome' => 'Augusto Pestana', 'uf' => 'RS'],
            ['codigo' => 3847, 'nome' => 'Aurea', 'uf' => 'RS'],
            ['codigo' => 3848, 'nome' => 'Bage', 'uf' => 'RS'],
            ['codigo' => 3849, 'nome' => 'Balneario Pinhal', 'uf' => 'RS'],
            ['codigo' => 3850, 'nome' => 'Barao', 'uf' => 'RS'],
            ['codigo' => 3851, 'nome' => 'Barao de Cotegipe', 'uf' => 'RS'],
            ['codigo' => 3852, 'nome' => 'Barao do Triunfo', 'uf' => 'RS'],
            ['codigo' => 3853, 'nome' => 'Barra do Guarita', 'uf' => 'RS'],
            ['codigo' => 3854, 'nome' => 'Barra do Quarai', 'uf' => 'RS'],
            ['codigo' => 3855, 'nome' => 'Barra do Ribeiro', 'uf' => 'RS'],
            ['codigo' => 3856, 'nome' => 'Barra do Rio Azul', 'uf' => 'RS'],
            ['codigo' => 3857, 'nome' => 'Barra Funda', 'uf' => 'RS'],
            ['codigo' => 3858, 'nome' => 'Barracao', 'uf' => 'RS'],
            ['codigo' => 3859, 'nome' => 'Barros Cassal', 'uf' => 'RS'],
            ['codigo' => 3860, 'nome' => 'Benjamin Constant do Sul', 'uf' => 'RS'],
            ['codigo' => 3861, 'nome' => 'Bento Goncalves', 'uf' => 'RS'],
            ['codigo' => 3862, 'nome' => 'Boa Vista das Missoes', 'uf' => 'RS'],
            ['codigo' => 3863, 'nome' => 'Boa Vista do Burica', 'uf' => 'RS'],
            ['codigo' => 3864, 'nome' => 'Boa Vista do Sul', 'uf' => 'RS'],
            ['codigo' => 3865, 'nome' => 'Bom Jesus', 'uf' => 'RS'],
            ['codigo' => 3866, 'nome' => 'Bom Principio', 'uf' => 'RS'],
            ['codigo' => 3867, 'nome' => 'Bom Progresso', 'uf' => 'RS'],
            ['codigo' => 3868, 'nome' => 'Bom Retiro do Sul', 'uf' => 'RS'],
            ['codigo' => 3869, 'nome' => 'Boqueirao do Leao', 'uf' => 'RS'],
            ['codigo' => 3870, 'nome' => 'Bossoroca', 'uf' => 'RS'],
            ['codigo' => 3871, 'nome' => 'Braga', 'uf' => 'RS'],
            ['codigo' => 3872, 'nome' => 'Brochier', 'uf' => 'RS'],
            ['codigo' => 3873, 'nome' => 'Butia', 'uf' => 'RS'],
            ['codigo' => 3874, 'nome' => 'Cacapava do Sul', 'uf' => 'RS'],
            ['codigo' => 3875, 'nome' => 'Cacequi', 'uf' => 'RS'],
            ['codigo' => 3876, 'nome' => 'Cachoeira do Sul', 'uf' => 'RS'],
            ['codigo' => 3877, 'nome' => 'Cachoeirinha', 'uf' => 'RS'],
            ['codigo' => 3878, 'nome' => 'Cacique Doble', 'uf' => 'RS'],
            ['codigo' => 3879, 'nome' => 'Caibate', 'uf' => 'RS'],
            ['codigo' => 3880, 'nome' => 'Caicara', 'uf' => 'RS'],
            ['codigo' => 3881, 'nome' => 'Camaqua', 'uf' => 'RS'],
            ['codigo' => 3882, 'nome' => 'Camargo', 'uf' => 'RS'],
            ['codigo' => 3883, 'nome' => 'Cambara do Sul', 'uf' => 'RS'],
            ['codigo' => 3884, 'nome' => 'Campestre da Serra', 'uf' => 'RS'],
            ['codigo' => 3885, 'nome' => 'Campina das Missoes', 'uf' => 'RS'],
            ['codigo' => 3886, 'nome' => 'Campinas do Sul', 'uf' => 'RS'],
            ['codigo' => 3887, 'nome' => 'Campo Bom', 'uf' => 'RS'],
            ['codigo' => 3888, 'nome' => 'Campo Novo', 'uf' => 'RS'],
            ['codigo' => 3889, 'nome' => 'Campos Borges', 'uf' => 'RS'],
            ['codigo' => 3890, 'nome' => 'Candelaria', 'uf' => 'RS'],
            ['codigo' => 3891, 'nome' => 'Candido Godoi', 'uf' => 'RS'],
            ['codigo' => 3892, 'nome' => 'Candiota', 'uf' => 'RS'],
            ['codigo' => 3893, 'nome' => 'Canela', 'uf' => 'RS'],
            ['codigo' => 3894, 'nome' => 'Cangucu', 'uf' => 'RS'],
            ['codigo' => 3895, 'nome' => 'Canoas', 'uf' => 'RS'],
            ['codigo' => 3896, 'nome' => 'Capao da Canoa', 'uf' => 'RS'],
            ['codigo' => 3897, 'nome' => 'Capao do Leao', 'uf' => 'RS'],
            ['codigo' => 3898, 'nome' => 'Capela de Santana', 'uf' => 'RS'],
            ['codigo' => 3899, 'nome' => 'Capitao', 'uf' => 'RS'],
            ['codigo' => 3900, 'nome' => 'Capivari do Sul', 'uf' => 'RS'],
            ['codigo' => 3901, 'nome' => 'Caraa', 'uf' => 'RS'],
            ['codigo' => 3902, 'nome' => 'Carazinho', 'uf' => 'RS'],
            ['codigo' => 3903, 'nome' => 'Carlos Barbosa', 'uf' => 'RS'],
            ['codigo' => 3904, 'nome' => 'Carlos Gomes', 'uf' => 'RS'],
            ['codigo' => 3905, 'nome' => 'Casca', 'uf' => 'RS'],
            ['codigo' => 3906, 'nome' => 'Caseiros', 'uf' => 'RS'],
            ['codigo' => 3907, 'nome' => 'Catuipe', 'uf' => 'RS'],
            ['codigo' => 3908, 'nome' => 'Caxias do Sul', 'uf' => 'RS'],
            ['codigo' => 3909, 'nome' => 'Centenario', 'uf' => 'RS'],
            ['codigo' => 3910, 'nome' => 'Cerrito', 'uf' => 'RS'],
            ['codigo' => 3911, 'nome' => 'Cerro Branco', 'uf' => 'RS'],
            ['codigo' => 3912, 'nome' => 'Cerro Grande', 'uf' => 'RS'],
            ['codigo' => 3913, 'nome' => 'Cerro Grande do Sul', 'uf' => 'RS'],
            ['codigo' => 3914, 'nome' => 'Cerro Largo', 'uf' => 'RS'],
            ['codigo' => 3915, 'nome' => 'Chapada', 'uf' => 'RS'],
            ['codigo' => 3916, 'nome' => 'Charqueadas', 'uf' => 'RS'],
            ['codigo' => 3917, 'nome' => 'Charrua', 'uf' => 'RS'],
            ['codigo' => 3918, 'nome' => 'Chiapeta', 'uf' => 'RS'],
            ['codigo' => 3919, 'nome' => 'Chui', 'uf' => 'RS'],
            ['codigo' => 3920, 'nome' => 'Chuvisca', 'uf' => 'RS'],
            ['codigo' => 3921, 'nome' => 'Cidreira', 'uf' => 'RS'],
            ['codigo' => 3922, 'nome' => 'Ciriaco', 'uf' => 'RS'],
            ['codigo' => 3923, 'nome' => 'Colinas', 'uf' => 'RS'],
            ['codigo' => 3924, 'nome' => 'Colorado', 'uf' => 'RS'],
            ['codigo' => 3925, 'nome' => 'Condor', 'uf' => 'RS'],
            ['codigo' => 3926, 'nome' => 'Constantina', 'uf' => 'RS'],
            ['codigo' => 3927, 'nome' => 'Coqueiros do Sul', 'uf' => 'RS'],
            ['codigo' => 3928, 'nome' => 'Coronel Barros', 'uf' => 'RS'],
            ['codigo' => 3929, 'nome' => 'Coronel Bicaco', 'uf' => 'RS'],
            ['codigo' => 3930, 'nome' => 'Cotipora', 'uf' => 'RS'],
            ['codigo' => 3931, 'nome' => 'Coxilha', 'uf' => 'RS'],
            ['codigo' => 3932, 'nome' => 'Crissiumal', 'uf' => 'RS'],
            ['codigo' => 3933, 'nome' => 'Cristal', 'uf' => 'RS'],
            ['codigo' => 3934, 'nome' => 'Cristal do Sul', 'uf' => 'RS'],
            ['codigo' => 3935, 'nome' => 'Cruz Alta', 'uf' => 'RS'],
            ['codigo' => 3936, 'nome' => 'Cruzeiro do Sul', 'uf' => 'RS'],
            ['codigo' => 3937, 'nome' => 'David Canabarro', 'uf' => 'RS'],
            ['codigo' => 3938, 'nome' => 'Derrubadas', 'uf' => 'RS'],
            ['codigo' => 3939, 'nome' => 'Dezesseis de Novembro', 'uf' => 'RS'],
            ['codigo' => 3940, 'nome' => 'Dilermando de Aguiar', 'uf' => 'RS'],
            ['codigo' => 3941, 'nome' => 'Dois Irmaos', 'uf' => 'RS'],
            ['codigo' => 3942, 'nome' => 'Dois Irmaos das Missoes', 'uf' => 'RS'],
            ['codigo' => 3943, 'nome' => 'Dois Lajeados', 'uf' => 'RS'],
            ['codigo' => 3944, 'nome' => 'Dom Feliciano', 'uf' => 'RS'],
            ['codigo' => 3945, 'nome' => 'Dom Pedrito', 'uf' => 'RS'],
            ['codigo' => 3946, 'nome' => 'Dom Pedro de Alcantara', 'uf' => 'RS'],
            ['codigo' => 3947, 'nome' => 'Dona Francisca', 'uf' => 'RS'],
            ['codigo' => 3948, 'nome' => 'Doutor Mauricio Cardoso', 'uf' => 'RS'],
            ['codigo' => 3949, 'nome' => 'Doutor Ricardo', 'uf' => 'RS'],
            ['codigo' => 3950, 'nome' => 'Eldorado do Sul', 'uf' => 'RS'],
            ['codigo' => 3951, 'nome' => 'Encantado', 'uf' => 'RS'],
            ['codigo' => 3952, 'nome' => 'Encruzilhada do Sul', 'uf' => 'RS'],
            ['codigo' => 3953, 'nome' => 'Engenho Velho', 'uf' => 'RS'],
            ['codigo' => 3954, 'nome' => 'Entre Rios do Sul', 'uf' => 'RS'],
            ['codigo' => 3955, 'nome' => 'Entre-Ijuis', 'uf' => 'RS'],
            ['codigo' => 3956, 'nome' => 'Erebango', 'uf' => 'RS'],
            ['codigo' => 3957, 'nome' => 'Erechim', 'uf' => 'RS'],
            ['codigo' => 3958, 'nome' => 'Ernestina', 'uf' => 'RS'],
            ['codigo' => 3959, 'nome' => 'Erval Grande', 'uf' => 'RS'],
            ['codigo' => 3960, 'nome' => 'Erval Seco', 'uf' => 'RS'],
            ['codigo' => 3961, 'nome' => 'Esmeralda', 'uf' => 'RS'],
            ['codigo' => 3962, 'nome' => 'Esperanca do Sul', 'uf' => 'RS'],
            ['codigo' => 3963, 'nome' => 'Espumoso', 'uf' => 'RS'],
            ['codigo' => 3964, 'nome' => 'Estacao', 'uf' => 'RS'],
            ['codigo' => 3965, 'nome' => 'Estancia Velha', 'uf' => 'RS'],
            ['codigo' => 3966, 'nome' => 'Esteio', 'uf' => 'RS'],
            ['codigo' => 3967, 'nome' => 'Estrela', 'uf' => 'RS'],
            ['codigo' => 3968, 'nome' => 'Estrela Velha', 'uf' => 'RS'],
            ['codigo' => 3969, 'nome' => 'Eugenio de Castro', 'uf' => 'RS'],
            ['codigo' => 3970, 'nome' => 'Fagundes Varela', 'uf' => 'RS'],
            ['codigo' => 3971, 'nome' => 'Farroupilha', 'uf' => 'RS'],
            ['codigo' => 3972, 'nome' => 'Faxinal do Soturno', 'uf' => 'RS'],
            ['codigo' => 3973, 'nome' => 'Faxinalzinho', 'uf' => 'RS'],
            ['codigo' => 3974, 'nome' => 'Fazenda Vilanova', 'uf' => 'RS'],
            ['codigo' => 3975, 'nome' => 'Feliz', 'uf' => 'RS'],
            ['codigo' => 3976, 'nome' => 'Flores da Cunha', 'uf' => 'RS'],
            ['codigo' => 3977, 'nome' => 'Floriano Peixoto', 'uf' => 'RS'],
            ['codigo' => 3978, 'nome' => 'Fontoura Xavier', 'uf' => 'RS'],
            ['codigo' => 3979, 'nome' => 'Formigueiro', 'uf' => 'RS'],
            ['codigo' => 3980, 'nome' => 'Fortaleza dos Valos', 'uf' => 'RS'],
            ['codigo' => 3981, 'nome' => 'Frederico Westphalen', 'uf' => 'RS'],
            ['codigo' => 3982, 'nome' => 'Garibaldi', 'uf' => 'RS'],
            ['codigo' => 3983, 'nome' => 'Garruchos', 'uf' => 'RS'],
            ['codigo' => 3984, 'nome' => 'Gaurama', 'uf' => 'RS'],
            ['codigo' => 3985, 'nome' => 'General Camara', 'uf' => 'RS'],
            ['codigo' => 3986, 'nome' => 'Gentil', 'uf' => 'RS'],
            ['codigo' => 3987, 'nome' => 'Getúlio Vargas', 'uf' => 'RS'],
            ['codigo' => 3988, 'nome' => 'Girua', 'uf' => 'RS'],
            ['codigo' => 3989, 'nome' => 'Glorinha', 'uf' => 'RS'],
            ['codigo' => 3990, 'nome' => 'Gramado', 'uf' => 'RS'],
            ['codigo' => 3991, 'nome' => 'Gramado dos Loureiros', 'uf' => 'RS'],
            ['codigo' => 3992, 'nome' => 'Gramado Xavier', 'uf' => 'RS'],
            ['codigo' => 3993, 'nome' => 'Gravatai', 'uf' => 'RS'],
            ['codigo' => 3994, 'nome' => 'Guabiju', 'uf' => 'RS'],
            ['codigo' => 3995, 'nome' => 'Guaiba', 'uf' => 'RS'],
            ['codigo' => 3996, 'nome' => 'Guapore', 'uf' => 'RS'],
            ['codigo' => 3997, 'nome' => 'Guarani das Missoes', 'uf' => 'RS'],
            ['codigo' => 3998, 'nome' => 'Harmonia', 'uf' => 'RS'],
            ['codigo' => 3999, 'nome' => 'Herval', 'uf' => 'RS'],
            ['codigo' => 4000, 'nome' => 'Herveiras', 'uf' => 'RS'],
            ['codigo' => 4001, 'nome' => 'Horizontina', 'uf' => 'RS'],
            ['codigo' => 4002, 'nome' => 'Hulha Negra', 'uf' => 'RS'],
            ['codigo' => 4003, 'nome' => 'Humaita', 'uf' => 'RS'],
            ['codigo' => 4004, 'nome' => 'Ibarama', 'uf' => 'RS'],
            ['codigo' => 4005, 'nome' => 'Ibiaca', 'uf' => 'RS'],
            ['codigo' => 4006, 'nome' => 'Ibiraiaras', 'uf' => 'RS'],
            ['codigo' => 4007, 'nome' => 'Ibirapuita', 'uf' => 'RS'],
            ['codigo' => 4008, 'nome' => 'Ibiruba', 'uf' => 'RS'],
            ['codigo' => 4009, 'nome' => 'Igrejinha', 'uf' => 'RS'],
            ['codigo' => 4010, 'nome' => 'Ijui', 'uf' => 'RS'],
            ['codigo' => 4011, 'nome' => 'Ilopolis', 'uf' => 'RS'],
            ['codigo' => 4012, 'nome' => 'Imbe', 'uf' => 'RS'],
            ['codigo' => 4013, 'nome' => 'Imigrante', 'uf' => 'RS'],
            ['codigo' => 4014, 'nome' => 'Independencia', 'uf' => 'RS'],
            ['codigo' => 4015, 'nome' => 'Inhacora', 'uf' => 'RS'],
            ['codigo' => 4016, 'nome' => 'Ipe', 'uf' => 'RS'],
            ['codigo' => 4017, 'nome' => 'Ipiranga do Sul', 'uf' => 'RS'],
            ['codigo' => 4018, 'nome' => 'Irai', 'uf' => 'RS'],
            ['codigo' => 4019, 'nome' => 'Itaara', 'uf' => 'RS'],
            ['codigo' => 4020, 'nome' => 'Itacurubi', 'uf' => 'RS'],
            ['codigo' => 4021, 'nome' => 'Itapuca', 'uf' => 'RS'],
            ['codigo' => 4022, 'nome' => 'Itaqui', 'uf' => 'RS'],
            ['codigo' => 4023, 'nome' => 'Itatiba do Sul', 'uf' => 'RS'],
            ['codigo' => 4024, 'nome' => 'Ivora', 'uf' => 'RS'],
            ['codigo' => 4025, 'nome' => 'Ivoti', 'uf' => 'RS'],
            ['codigo' => 4026, 'nome' => 'Jaboticaba', 'uf' => 'RS'],
            ['codigo' => 4027, 'nome' => 'Jacutinga', 'uf' => 'RS'],
            ['codigo' => 4028, 'nome' => 'Jaguarao', 'uf' => 'RS'],
            ['codigo' => 4029, 'nome' => 'Jaguari', 'uf' => 'RS'],
            ['codigo' => 4030, 'nome' => 'Jaquirana', 'uf' => 'RS'],
            ['codigo' => 4031, 'nome' => 'Jari', 'uf' => 'RS'],
            ['codigo' => 4032, 'nome' => 'Joia', 'uf' => 'RS'],
            ['codigo' => 4033, 'nome' => 'Júlio de Castilhos', 'uf' => 'RS'],
            ['codigo' => 4034, 'nome' => 'Lagoa dos Tres Cantos', 'uf' => 'RS'],
            ['codigo' => 4035, 'nome' => 'Lagoa Vermelha', 'uf' => 'RS'],
            ['codigo' => 4036, 'nome' => 'Lagoao', 'uf' => 'RS'],
            ['codigo' => 4037, 'nome' => 'Lajeado', 'uf' => 'RS'],
            ['codigo' => 4038, 'nome' => 'Lajeado do Bugre', 'uf' => 'RS'],
            ['codigo' => 4039, 'nome' => 'Lavras do Sul', 'uf' => 'RS'],
            ['codigo' => 4040, 'nome' => 'Liberato Salzano', 'uf' => 'RS'],
            ['codigo' => 4041, 'nome' => 'Lindolfo Collor', 'uf' => 'RS'],
            ['codigo' => 4042, 'nome' => 'Linha Nova', 'uf' => 'RS'],
            ['codigo' => 4043, 'nome' => 'Macambara', 'uf' => 'RS'],
            ['codigo' => 4044, 'nome' => 'Machadinho', 'uf' => 'RS'],
            ['codigo' => 4045, 'nome' => 'Mampituba', 'uf' => 'RS'],
            ['codigo' => 4046, 'nome' => 'Manoel Viana', 'uf' => 'RS'],
            ['codigo' => 4047, 'nome' => 'Maquine', 'uf' => 'RS'],
            ['codigo' => 4048, 'nome' => 'Marata', 'uf' => 'RS'],
            ['codigo' => 4049, 'nome' => 'Marau', 'uf' => 'RS'],
            ['codigo' => 4050, 'nome' => 'Marcelino Ramos', 'uf' => 'RS'],
            ['codigo' => 4051, 'nome' => 'Mariana Pimentel', 'uf' => 'RS'],
            ['codigo' => 4052, 'nome' => 'Mariano Moro', 'uf' => 'RS'],
            ['codigo' => 4053, 'nome' => 'Marques de Souza', 'uf' => 'RS'],
            ['codigo' => 4054, 'nome' => 'Mata', 'uf' => 'RS'],
            ['codigo' => 4055, 'nome' => 'Mato Castelhano', 'uf' => 'RS'],
            ['codigo' => 4056, 'nome' => 'Mato Leitao', 'uf' => 'RS'],
            ['codigo' => 4057, 'nome' => 'Maximiliano de Almeida', 'uf' => 'RS'],
            ['codigo' => 4058, 'nome' => 'Minas do Leao', 'uf' => 'RS'],
            ['codigo' => 4059, 'nome' => 'Miraguai', 'uf' => 'RS'],
            ['codigo' => 4060, 'nome' => 'Montauri', 'uf' => 'RS'],
            ['codigo' => 4061, 'nome' => 'Monte Alegre dos Campos', 'uf' => 'RS'],
            ['codigo' => 4062, 'nome' => 'Monte Belo do Sul', 'uf' => 'RS'],
            ['codigo' => 4063, 'nome' => 'Montenegro', 'uf' => 'RS'],
            ['codigo' => 4064, 'nome' => 'Mormaco', 'uf' => 'RS'],
            ['codigo' => 4065, 'nome' => 'Morrinhos do Sul', 'uf' => 'RS'],
            ['codigo' => 4066, 'nome' => 'Morro Redondo', 'uf' => 'RS'],
            ['codigo' => 4067, 'nome' => 'Morro Reuter', 'uf' => 'RS'],
            ['codigo' => 4068, 'nome' => 'Mostardas', 'uf' => 'RS'],
            ['codigo' => 4069, 'nome' => 'Mucum', 'uf' => 'RS'],
            ['codigo' => 4070, 'nome' => 'Muitos Capoes', 'uf' => 'RS'],
            ['codigo' => 4071, 'nome' => 'Muliterno', 'uf' => 'RS'],
            ['codigo' => 4072, 'nome' => 'Nao-Me-Toque', 'uf' => 'RS'],
            ['codigo' => 4073, 'nome' => 'Nicolau Vergueiro', 'uf' => 'RS'],
            ['codigo' => 4074, 'nome' => 'Nonoai', 'uf' => 'RS'],
            ['codigo' => 4075, 'nome' => 'Nova Alvorada', 'uf' => 'RS'],
            ['codigo' => 4076, 'nome' => 'Nova Araca', 'uf' => 'RS'],
            ['codigo' => 4077, 'nome' => 'Nova Bassano', 'uf' => 'RS'],
            ['codigo' => 4078, 'nome' => 'Nova Boa Vista', 'uf' => 'RS'],
            ['codigo' => 4079, 'nome' => 'Nova Brescia', 'uf' => 'RS'],
            ['codigo' => 4080, 'nome' => 'Nova Candelaria', 'uf' => 'RS'],
            ['codigo' => 4081, 'nome' => 'Nova Esperanca do Sul', 'uf' => 'RS'],
            ['codigo' => 4082, 'nome' => 'Nova Hartz', 'uf' => 'RS'],
            ['codigo' => 4083, 'nome' => 'Nova Padua', 'uf' => 'RS'],
            ['codigo' => 4084, 'nome' => 'Nova Palma', 'uf' => 'RS'],
            ['codigo' => 4085, 'nome' => 'Nova Petropolis', 'uf' => 'RS'],
            ['codigo' => 4086, 'nome' => 'Nova Prata', 'uf' => 'RS'],
            ['codigo' => 4087, 'nome' => 'Nova Ramada', 'uf' => 'RS'],
            ['codigo' => 4088, 'nome' => 'Nova Roma do Sul', 'uf' => 'RS'],
            ['codigo' => 4089, 'nome' => 'Nova Santa Rita', 'uf' => 'RS'],
            ['codigo' => 4090, 'nome' => 'Novo Barreiro', 'uf' => 'RS'],
            ['codigo' => 4091, 'nome' => 'Novo Cabrais', 'uf' => 'RS'],
            ['codigo' => 4092, 'nome' => 'Novo Hamburgo', 'uf' => 'RS'],
            ['codigo' => 4093, 'nome' => 'Novo Machado', 'uf' => 'RS'],
            ['codigo' => 4094, 'nome' => 'Novo Tiradentes', 'uf' => 'RS'],
            ['codigo' => 4095, 'nome' => 'Osorio', 'uf' => 'RS'],
            ['codigo' => 4096, 'nome' => 'Paim Filho', 'uf' => 'RS'],
            ['codigo' => 4097, 'nome' => 'Palmares do Sul', 'uf' => 'RS'],
            ['codigo' => 4098, 'nome' => 'Palmeira das Missoes', 'uf' => 'RS'],
            ['codigo' => 4099, 'nome' => 'Palmitinho', 'uf' => 'RS'],
            ['codigo' => 4100, 'nome' => 'Panambi', 'uf' => 'RS'],
            ['codigo' => 4101, 'nome' => 'Pantano Grande', 'uf' => 'RS'],
            ['codigo' => 4102, 'nome' => 'Parai', 'uf' => 'RS'],
            ['codigo' => 4103, 'nome' => 'Paraiso do Sul', 'uf' => 'RS'],
            ['codigo' => 4104, 'nome' => 'Pareci Novo', 'uf' => 'RS'],
            ['codigo' => 4105, 'nome' => 'Parobe', 'uf' => 'RS'],
            ['codigo' => 4106, 'nome' => 'Passa Sete', 'uf' => 'RS'],
            ['codigo' => 4107, 'nome' => 'Passo do Sobrado', 'uf' => 'RS'],
            ['codigo' => 4108, 'nome' => 'Passo Fundo', 'uf' => 'RS'],
            ['codigo' => 4109, 'nome' => 'Paverama', 'uf' => 'RS'],
            ['codigo' => 4110, 'nome' => 'Pedro Osorio', 'uf' => 'RS'],
            ['codigo' => 4111, 'nome' => 'Pejucara', 'uf' => 'RS'],
            ['codigo' => 4112, 'nome' => 'Pelotas', 'uf' => 'RS'],
            ['codigo' => 4113, 'nome' => 'Picada Cafe', 'uf' => 'RS'],
            ['codigo' => 4114, 'nome' => 'Pinhal', 'uf' => 'RS'],
            ['codigo' => 4115, 'nome' => 'Pinhal Grande', 'uf' => 'RS'],
            ['codigo' => 4116, 'nome' => 'Pinheirinho do Vale', 'uf' => 'RS'],
            ['codigo' => 4117, 'nome' => 'Pinheiro Machado', 'uf' => 'RS'],
            ['codigo' => 4118, 'nome' => 'Pirapo', 'uf' => 'RS'],
            ['codigo' => 4119, 'nome' => 'Piratini', 'uf' => 'RS'],
            ['codigo' => 4120, 'nome' => 'Planalto', 'uf' => 'RS'],
            ['codigo' => 4121, 'nome' => 'Poco das Antas', 'uf' => 'RS'],
            ['codigo' => 4122, 'nome' => 'Pontao', 'uf' => 'RS'],
            ['codigo' => 4123, 'nome' => 'Ponte Preta', 'uf' => 'RS'],
            ['codigo' => 4124, 'nome' => 'Portao', 'uf' => 'RS'],
            ['codigo' => 4125, 'nome' => 'Porto Alegre', 'uf' => 'RS'],
            ['codigo' => 4126, 'nome' => 'Porto Lucena', 'uf' => 'RS'],
            ['codigo' => 4127, 'nome' => 'Porto Maua', 'uf' => 'RS'],
            ['codigo' => 4128, 'nome' => 'Porto Vera Cruz', 'uf' => 'RS'],
            ['codigo' => 4129, 'nome' => 'Porto Xavier', 'uf' => 'RS'],
            ['codigo' => 4130, 'nome' => 'Pouso Novo', 'uf' => 'RS'],
            ['codigo' => 4131, 'nome' => 'Presidente Lucena', 'uf' => 'RS'],
            ['codigo' => 4132, 'nome' => 'Progresso', 'uf' => 'RS'],
            ['codigo' => 4133, 'nome' => 'Protasio Alves', 'uf' => 'RS'],
            ['codigo' => 4134, 'nome' => 'Putinga', 'uf' => 'RS'],
            ['codigo' => 4135, 'nome' => 'Quarai', 'uf' => 'RS'],
            ['codigo' => 4136, 'nome' => 'Quevedos', 'uf' => 'RS'],
            ['codigo' => 4137, 'nome' => 'Quinze de Novembro', 'uf' => 'RS'],
            ['codigo' => 4138, 'nome' => 'Redentora', 'uf' => 'RS'],
            ['codigo' => 4139, 'nome' => 'Relvado', 'uf' => 'RS'],
            ['codigo' => 4140, 'nome' => 'Restinga Seca', 'uf' => 'RS'],
            ['codigo' => 4141, 'nome' => 'Rio dos indios', 'uf' => 'RS'],
            ['codigo' => 4142, 'nome' => 'Rio Grande', 'uf' => 'RS'],
            ['codigo' => 4143, 'nome' => 'Rio Pardo', 'uf' => 'RS'],
            ['codigo' => 4144, 'nome' => 'Riozinho', 'uf' => 'RS'],
            ['codigo' => 4145, 'nome' => 'Roca Sales', 'uf' => 'RS'],
            ['codigo' => 4146, 'nome' => 'Rodeio Bonito', 'uf' => 'RS'],
            ['codigo' => 4147, 'nome' => 'Rolante', 'uf' => 'RS'],
            ['codigo' => 4148, 'nome' => 'Ronda Alta', 'uf' => 'RS'],
            ['codigo' => 4149, 'nome' => 'Rondinha', 'uf' => 'RS'],
            ['codigo' => 4150, 'nome' => 'Roque Gonzales', 'uf' => 'RS'],
            ['codigo' => 4151, 'nome' => 'Rosario do Sul', 'uf' => 'RS'],
            ['codigo' => 4152, 'nome' => 'Sagrada Familia', 'uf' => 'RS'],
            ['codigo' => 4153, 'nome' => 'Saldanha Marinho', 'uf' => 'RS'],
            ['codigo' => 4154, 'nome' => 'Salto do Jacui', 'uf' => 'RS'],
            ['codigo' => 4155, 'nome' => 'Salvador das Missoes', 'uf' => 'RS'],
            ['codigo' => 4156, 'nome' => 'Salvador do Sul', 'uf' => 'RS'],
            ['codigo' => 4157, 'nome' => 'Sananduva', 'uf' => 'RS'],
            ['codigo' => 4158, 'nome' => 'Santa Barbara do Sul', 'uf' => 'RS'],
            ['codigo' => 4159, 'nome' => 'Santa Clara do Sul', 'uf' => 'RS'],
            ['codigo' => 4160, 'nome' => 'Santa Cruz do Sul', 'uf' => 'RS'],
            ['codigo' => 4161, 'nome' => 'Santa Maria', 'uf' => 'RS'],
            ['codigo' => 4162, 'nome' => 'Santa Maria do Herval', 'uf' => 'RS'],
            ['codigo' => 4163, 'nome' => 'Santa Rosa', 'uf' => 'RS'],
            ['codigo' => 4164, 'nome' => 'Santa Tereza', 'uf' => 'RS'],
            ['codigo' => 4165, 'nome' => 'Santa Vitoria do Palmar', 'uf' => 'RS'],
            ['codigo' => 4166, 'nome' => 'Santana da Boa Vista', 'uf' => 'RS'],
            ['codigo' => 4167, 'nome' => 'Santana do Livramento', 'uf' => 'RS'],
            ['codigo' => 4168, 'nome' => 'Santiago', 'uf' => 'RS'],
            ['codigo' => 4169, 'nome' => 'Santo angelo', 'uf' => 'RS'],
            ['codigo' => 4170, 'nome' => 'Santo Antonio da Patrulha', 'uf' => 'RS'],
            ['codigo' => 4171, 'nome' => 'Santo Antonio das Missoes', 'uf' => 'RS'],
            ['codigo' => 4172, 'nome' => 'Santo Antonio do Palma', 'uf' => 'RS'],
            ['codigo' => 4173, 'nome' => 'Santo Antonio do Planalto', 'uf' => 'RS'],
            ['codigo' => 4174, 'nome' => 'Santo Augusto', 'uf' => 'RS'],
            ['codigo' => 4175, 'nome' => 'Santo Cristo', 'uf' => 'RS'],
            ['codigo' => 4176, 'nome' => 'Santo Expedito do Sul', 'uf' => 'RS'],
            ['codigo' => 4177, 'nome' => 'Sao Borja', 'uf' => 'RS'],
            ['codigo' => 4178, 'nome' => 'Sao Domingos do Sul', 'uf' => 'RS'],
            ['codigo' => 4179, 'nome' => 'Sao Francisco de Assis', 'uf' => 'RS'],
            ['codigo' => 4180, 'nome' => 'Sao Francisco de Paula', 'uf' => 'RS'],
            ['codigo' => 4181, 'nome' => 'Sao Gabriel', 'uf' => 'RS'],
            ['codigo' => 4182, 'nome' => 'Sao Jeronimo', 'uf' => 'RS'],
            ['codigo' => 4183, 'nome' => 'Sao Joao da Urtiga', 'uf' => 'RS'],
            ['codigo' => 4184, 'nome' => 'Sao Joao do Polesine', 'uf' => 'RS'],
            ['codigo' => 4185, 'nome' => 'Sao Jorge', 'uf' => 'RS'],
            ['codigo' => 4186, 'nome' => 'Sao Jose das Missoes', 'uf' => 'RS'],
            ['codigo' => 4187, 'nome' => 'Sao Jose do Herval', 'uf' => 'RS'],
            ['codigo' => 4188, 'nome' => 'Sao Jose do Hortencio', 'uf' => 'RS'],
            ['codigo' => 4189, 'nome' => 'Sao Jose do Inhacora', 'uf' => 'RS'],
            ['codigo' => 4190, 'nome' => 'Sao Jose do Norte', 'uf' => 'RS'],
            ['codigo' => 4191, 'nome' => 'Sao Jose do Ouro', 'uf' => 'RS'],
            ['codigo' => 4192, 'nome' => 'Sao Jose dos Ausentes', 'uf' => 'RS'],
            ['codigo' => 4193, 'nome' => 'Sao Leopoldo', 'uf' => 'RS'],
            ['codigo' => 4194, 'nome' => 'Sao Lourenco do Sul', 'uf' => 'RS'],
            ['codigo' => 4195, 'nome' => 'Sao Luiz Gonzaga', 'uf' => 'RS'],
            ['codigo' => 4196, 'nome' => 'Sao Marcos', 'uf' => 'RS'],
            ['codigo' => 4197, 'nome' => 'Sao Martinho', 'uf' => 'RS'],
            ['codigo' => 4198, 'nome' => 'Sao Martinho da Serra', 'uf' => 'RS'],
            ['codigo' => 4199, 'nome' => 'Sao Miguel das Missoes', 'uf' => 'RS'],
            ['codigo' => 4200, 'nome' => 'Sao Nicolau', 'uf' => 'RS'],
            ['codigo' => 4201, 'nome' => 'Sao Paulo das Missoes', 'uf' => 'RS'],
            ['codigo' => 4202, 'nome' => 'Sao Pedro da Serra', 'uf' => 'RS'],
            ['codigo' => 4203, 'nome' => 'Sao Pedro do Butia', 'uf' => 'RS'],
            ['codigo' => 4204, 'nome' => 'Sao Pedro do Sul', 'uf' => 'RS'],
            ['codigo' => 4205, 'nome' => 'Sao Sebastiao do Cai', 'uf' => 'RS'],
            ['codigo' => 4206, 'nome' => 'Sao Sepe', 'uf' => 'RS'],
            ['codigo' => 4207, 'nome' => 'Sao Valentim', 'uf' => 'RS'],
            ['codigo' => 4208, 'nome' => 'Sao Valentim do Sul', 'uf' => 'RS'],
            ['codigo' => 4209, 'nome' => 'Sao Valerio do Sul', 'uf' => 'RS'],
            ['codigo' => 4210, 'nome' => 'Sao Vendelino', 'uf' => 'RS'],
            ['codigo' => 4211, 'nome' => 'Sao Vicente do Sul', 'uf' => 'RS'],
            ['codigo' => 4212, 'nome' => 'Sapiranga', 'uf' => 'RS'],
            ['codigo' => 4213, 'nome' => 'Sapucaia do Sul', 'uf' => 'RS'],
            ['codigo' => 4214, 'nome' => 'Sarandi', 'uf' => 'RS'],
            ['codigo' => 4215, 'nome' => 'Seberi', 'uf' => 'RS'],
            ['codigo' => 4216, 'nome' => 'Sede Nova', 'uf' => 'RS'],
            ['codigo' => 4217, 'nome' => 'Segredo', 'uf' => 'RS'],
            ['codigo' => 4218, 'nome' => 'Selbach', 'uf' => 'RS'],
            ['codigo' => 4219, 'nome' => 'Senador Salgado Filho', 'uf' => 'RS'],
            ['codigo' => 4220, 'nome' => 'Sentinela do Sul', 'uf' => 'RS'],
            ['codigo' => 4221, 'nome' => 'Serafina Correa', 'uf' => 'RS'],
            ['codigo' => 4222, 'nome' => 'Serio', 'uf' => 'RS'],
            ['codigo' => 4223, 'nome' => 'Sertao', 'uf' => 'RS'],
            ['codigo' => 4224, 'nome' => 'Sertao Santana', 'uf' => 'RS'],
            ['codigo' => 4225, 'nome' => 'Sete de Setembro', 'uf' => 'RS'],
            ['codigo' => 4226, 'nome' => 'Severiano de Almeida', 'uf' => 'RS'],
            ['codigo' => 4227, 'nome' => 'Silveira Martins', 'uf' => 'RS'],
            ['codigo' => 4228, 'nome' => 'Sinimbu', 'uf' => 'RS'],
            ['codigo' => 4229, 'nome' => 'Sobradinho', 'uf' => 'RS'],
            ['codigo' => 4230, 'nome' => 'Soledade', 'uf' => 'RS'],
            ['codigo' => 4231, 'nome' => 'Tabai', 'uf' => 'RS'],
            ['codigo' => 4232, 'nome' => 'Tapejara', 'uf' => 'RS'],
            ['codigo' => 4233, 'nome' => 'Tapera', 'uf' => 'RS'],
            ['codigo' => 4234, 'nome' => 'Tapes', 'uf' => 'RS'],
            ['codigo' => 4235, 'nome' => 'Taquara', 'uf' => 'RS'],
            ['codigo' => 4236, 'nome' => 'Taquari', 'uf' => 'RS'],
            ['codigo' => 4237, 'nome' => 'Taquarucu do Sul', 'uf' => 'RS'],
            ['codigo' => 4238, 'nome' => 'Tavares', 'uf' => 'RS'],
            ['codigo' => 4239, 'nome' => 'Tenente Portela', 'uf' => 'RS'],
            ['codigo' => 4240, 'nome' => 'Terra de Areia', 'uf' => 'RS'],
            ['codigo' => 4241, 'nome' => 'Teutonia', 'uf' => 'RS'],
            ['codigo' => 4242, 'nome' => 'Tiradentes do Sul', 'uf' => 'RS'],
            ['codigo' => 4243, 'nome' => 'Toropi', 'uf' => 'RS'],
            ['codigo' => 4244, 'nome' => 'Torres', 'uf' => 'RS'],
            ['codigo' => 4245, 'nome' => 'Tramandai', 'uf' => 'RS'],
            ['codigo' => 4246, 'nome' => 'Travesseiro', 'uf' => 'RS'],
            ['codigo' => 4247, 'nome' => 'Tres Arroios', 'uf' => 'RS'],
            ['codigo' => 4248, 'nome' => 'Tres Cachoeiras', 'uf' => 'RS'],
            ['codigo' => 4249, 'nome' => 'Tres Coroas', 'uf' => 'RS'],
            ['codigo' => 4250, 'nome' => 'Tres de Maio', 'uf' => 'RS'],
            ['codigo' => 4251, 'nome' => 'Tres Forquilhas', 'uf' => 'RS'],
            ['codigo' => 4252, 'nome' => 'Tres Palmeiras', 'uf' => 'RS'],
            ['codigo' => 4253, 'nome' => 'Tres Passos', 'uf' => 'RS'],
            ['codigo' => 4254, 'nome' => 'Trindade do Sul', 'uf' => 'RS'],
            ['codigo' => 4255, 'nome' => 'Triunfo', 'uf' => 'RS'],
            ['codigo' => 4256, 'nome' => 'Tucunduva', 'uf' => 'RS'],
            ['codigo' => 4257, 'nome' => 'Tunas', 'uf' => 'RS'],
            ['codigo' => 4258, 'nome' => 'Tupanci do Sul', 'uf' => 'RS'],
            ['codigo' => 4259, 'nome' => 'Tupancireta', 'uf' => 'RS'],
            ['codigo' => 4260, 'nome' => 'Tupandi', 'uf' => 'RS'],
            ['codigo' => 4261, 'nome' => 'Tuparendi', 'uf' => 'RS'],
            ['codigo' => 4262, 'nome' => 'Turucu', 'uf' => 'RS'],
            ['codigo' => 4263, 'nome' => 'Ubiretama', 'uf' => 'RS'],
            ['codigo' => 4264, 'nome' => 'Uniao da Serra', 'uf' => 'RS'],
            ['codigo' => 4265, 'nome' => 'Unistalda', 'uf' => 'RS'],
            ['codigo' => 4266, 'nome' => 'Uruguaiana', 'uf' => 'RS'],
            ['codigo' => 4267, 'nome' => 'Vacaria', 'uf' => 'RS'],
            ['codigo' => 4268, 'nome' => 'Vale do Sol', 'uf' => 'RS'],
            ['codigo' => 4269, 'nome' => 'Vale Real', 'uf' => 'RS'],
            ['codigo' => 4270, 'nome' => 'Vale Verde', 'uf' => 'RS'],
            ['codigo' => 4271, 'nome' => 'Vanini', 'uf' => 'RS'],
            ['codigo' => 4272, 'nome' => 'Venancio Aires', 'uf' => 'RS'],
            ['codigo' => 4273, 'nome' => 'Vera Cruz', 'uf' => 'RS'],
            ['codigo' => 4274, 'nome' => 'Veranopolis', 'uf' => 'RS'],
            ['codigo' => 4275, 'nome' => 'Vespasiano Correa', 'uf' => 'RS'],
            ['codigo' => 4276, 'nome' => 'Viadutos', 'uf' => 'RS'],
            ['codigo' => 4277, 'nome' => 'Viamao', 'uf' => 'RS'],
            ['codigo' => 4278, 'nome' => 'Vicente Dutra', 'uf' => 'RS'],
            ['codigo' => 4279, 'nome' => 'Victor Graeff', 'uf' => 'RS'],
            ['codigo' => 4280, 'nome' => 'Vila Flores', 'uf' => 'RS'],
            ['codigo' => 4281, 'nome' => 'Vila Langaro', 'uf' => 'RS'],
            ['codigo' => 4282, 'nome' => 'Vila Maria', 'uf' => 'RS'],
            ['codigo' => 4283, 'nome' => 'Vila Nova do Sul', 'uf' => 'RS'],
            ['codigo' => 4284, 'nome' => 'Vista Alegre', 'uf' => 'RS'],
            ['codigo' => 4285, 'nome' => 'Vista Alegre do Prata', 'uf' => 'RS'],
            ['codigo' => 4286, 'nome' => 'Vista Gaucha', 'uf' => 'RS'],
            ['codigo' => 4287, 'nome' => 'Vitoria das Missoes', 'uf' => 'RS'],
            ['codigo' => 4288, 'nome' => 'Xangri-la', 'uf' => 'RS']
        ];
        
        \App\Municipio::insert($municipios);
    }
}
